# Generated by Django 3.0.2 on 2020-11-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employeeregistration',
            fields=[
                ('stdid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('workrole', models.CharField(max_length=20)),
                ('emp_name', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
            ],
        ),
    ]
