# Generated by Django 3.0.2 on 2020-12-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='empselary',
            fields=[
                ('empid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=20)),
                ('empdata', models.CharField(max_length=20)),
                ('emptotalincome', models.IntegerField()),
                ('empgivenincome', models.IntegerField()),
                ('empremaningincome', models.IntegerField()),
                ('emprole', models.CharField(max_length=20)),
            ],
        ),
    ]
