# Generated by Django 3.0.2 on 2020-12-08 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_empselary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empselary',
            old_name='empdata',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='empselary',
            old_name='empgivenincome',
            new_name='employee_given_income',
        ),
        migrations.RenameField(
            model_name='empselary',
            old_name='empid',
            new_name='employee_id',
        ),
        migrations.RenameField(
            model_name='empselary',
            old_name='empname',
            new_name='employee_name',
        ),
        migrations.RenameField(
            model_name='empselary',
            old_name='empremaningincome',
            new_name='employee_remaning_income',
        ),
        migrations.RenameField(
            model_name='empselary',
            old_name='emprole',
            new_name='employee_role',
        ),
        migrations.RenameField(
            model_name='empselary',
            old_name='emptotalincome',
            new_name='employee_total_income',
        ),
    ]
