# Generated by Django 3.0.2 on 2020-12-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20201208_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='empselary1',
            fields=[
                ('employee_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('employee_monthely_income', models.IntegerField()),
                ('employee_total_income', models.IntegerField()),
                ('employee_given_income', models.IntegerField()),
                ('employee_remaning_income', models.IntegerField()),
                ('employee_role', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='empselary',
        ),
    ]
