# Generated by Django 3.0.2 on 2020-12-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20201208_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='empselary2',
            fields=[
                ('employee_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=20)),
                ('employee_address', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('employee_monthely_income', models.IntegerField()),
                ('employee_total_income', models.IntegerField()),
                ('employee_given_income', models.IntegerField()),
                ('employee_remaning_income', models.IntegerField()),
                ('employee_role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='studentfees',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=20)),
                ('student_address', models.CharField(max_length=20)),
                ('student_course', models.CharField(max_length=20)),
                ('admision_date', models.CharField(max_length=20)),
                ('total_fees', models.IntegerField()),
                ('given_fees', models.IntegerField()),
                ('remaning_fees', models.IntegerField()),
                ('course_duration', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='empselary1',
        ),
    ]
