# Generated by Django 3.0.2 on 2020-12-08 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_auto_20201208_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentfees',
            old_name='student_id',
            new_name='studid',
        ),
    ]
