# Generated by Django 3.0.2 on 2020-12-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_idcardgenerate'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminregistration',
            fields=[
                ('admin_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('workrole', models.CharField(max_length=20)),
                ('admin_name', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
            ],
        ),
    ]
