# Generated by Django 3.0.2 on 2020-12-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_adminregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='emprofile1',
            fields=[
                ('employees_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=20)),
                ('email_id', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
                ('teaching_subject', models.CharField(max_length=20)),
                ('presinting', models.CharField(max_length=20)),
                ('performance', models.CharField(max_length=20)),
                ('emplimage', models.ImageField(upload_to='')),
            ],
        ),
    ]
