# Generated by Django 3.0.2 on 2020-12-21 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_emprofile1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='emprofile1',
            new_name='emprofile',
        ),
    ]
