# Generated by Django 3.0.2 on 2020-12-21 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_auto_20201221_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprofile',
            name='email',
        ),
    ]
