# Generated by Django 3.0.2 on 2020-12-01 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empregistration',
            old_name='stdid',
            new_name='empid',
        ),
    ]
