# Generated by Django 3.0.2 on 2020-12-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_stprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='stprofile1',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('mobile', models.IntegerField(max_length=12)),
                ('email', models.CharField(max_length=20)),
                ('student_course1', models.CharField(max_length=20)),
                ('student_course2', models.CharField(max_length=20)),
                ('student_course3', models.CharField(max_length=20)),
                ('student_course4', models.CharField(max_length=20)),
                ('full_marks', models.IntegerField()),
                ('obtaind_marks', models.IntegerField()),
                ('grad', models.CharField(max_length=20)),
                ('percentage', models.CharField(max_length=20)),
                ('stdimage', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='stprofile',
        ),
    ]
