# Generated by Django 3.0.2 on 2020-12-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_stperformance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stperformance',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stprofile1',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
