# Generated by Django 3.0.2 on 2020-12-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20201221_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentperformance',
            fields=[
                ('studentsid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('mobile', models.IntegerField()),
                ('full_marks', models.IntegerField()),
                ('obtaind_marks', models.IntegerField()),
                ('grad', models.CharField(max_length=20)),
                ('percentage', models.CharField(max_length=20)),
                ('attendance', models.CharField(max_length=20)),
                ('student_type', models.CharField(max_length=20)),
                ('performance', models.CharField(max_length=20)),
                ('studimage', models.ImageField(upload_to='')),
            ],
        ),
    ]
