# Generated by Django 3.0.2 on 2020-11-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='idfetchs',
            fields=[
                ('idno', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
