# Generated by Django 3.0.2 on 2020-11-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='idfetch',
            fields=[
                ('idno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='idfetchs',
        ),
    ]
