# Generated by Django 3.0.2 on 2020-12-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201128_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='enquari',
            fields=[
                ('course', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('mobile', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
            ],
        ),
    ]
