# Generated by Django 3.0.2 on 2020-12-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_enquari'),
    ]

    operations = [
        migrations.CreateModel(
            name='enquari1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('mobile', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='enquari',
        ),
    ]
